dist: xenial
language: python
jobs:
  include:
  - python: "2.6"
    dist: trusty
  - python: "2.7"
  - python: pypy
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8-dev"
  - python: pypy3
branches:
  except:
  - appveyor
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_pylint=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then if_pylint=:; fi
install:
- pip install docutils pygments
- pip install pydiatra $pyflakes
- $if_pylint pip install pylint
before_script:
- distutils_pkg=$(python -c 'import os, distutils as d; print(os.path.dirname(d.__file__))')
- echo "$distutils_pkg" "$VIRTUAL_ENV"
- if [[ $distutils_pkg != "${VIRTUAL_ENV%/}"/* ]]; then if_vdistutils=:; fi
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- private/check-rst
- python -m pydiatra .
- pyflakes .
- $if_pylint $if_vdistutils mv $distutils_pkg{,.bak}
- $if_pylint python -m pylint *.py */*.py
- $if_pylint $if_vdistutils mv $distutils_pkg{.bak,}
- PYTHONPATH=$PWD python test/test.py --verbose
- LC_ALL=C python setup.py --version
- python setup.py install
- cd /
- python -c 'import slownie'

# vim:ts=2 sts=2 sw=2 et
